#!/usr/bin/env python
# -*- coding: us-ascii -*-
# vim: syntax=python
#
# Copyright 2006-2009 Noriyuki Hosaka bgnori@gmail.com
#


#WARNING!
#DO NOT EDIT THIS FILE.
#THIS FILE IS AUTO GENERATED.

import unittest
from bglib.record.snowietxt import Validator

class SnowietxtTest(unittest.TestCase):

  def test_0(self):
    f = open('bglib/record/testdata/1857680.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a1d23325d0c8a614756529de960e4e7bdc1f6737')

  def test_1(self):
    f = open('bglib/record/testdata/1857896.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1e5e9c42cca872ab0ae46532f8e5b4977a7e6b8f')

  def test_2(self):
    f = open('bglib/record/testdata/1859149.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '02eba07f8971414d50d0605839f2312225253ad9')

  def test_3(self):
    f = open('bglib/record/testdata/1863526.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '309e10bb0b0abb22a12524bbda17eeb65e3986af')

  def test_4(self):
    f = open('bglib/record/testdata/1863670.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c23a44aab1bcc543bb510ad19c2155b97014a688')

  def test_5(self):
    f = open('bglib/record/testdata/1864694.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9973f7ae617ad51b7e48a6cc07619ff3775f120d')

  def test_6(self):
    f = open('bglib/record/testdata/1865970.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e30d9b492364487badc45709f8689b634df13bd0')

  def test_7(self):
    f = open('bglib/record/testdata/1887435.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '610c5fee9f06e167c7510d9ba66e768d887474ad')

  def test_8(self):
    f = open('bglib/record/testdata/1896804.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f7b2863f5c0c0eaa2a8aea1b153ef843c7913903')

  def test_9(self):
    f = open('bglib/record/testdata/1900211.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f16fbe1bc5e7aa7a7f914685eadc53d4269b478e')

  def test_10(self):
    f = open('bglib/record/testdata/1900327.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1d17c7e5ae1132a313f7c553df07cec0b5f6b743')

  def test_11(self):
    f = open('bglib/record/testdata/1910477.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8ccdcc27114914a53404b32e49b868451f7d8d77')

  def test_12(self):
    f = open('bglib/record/testdata/1989-nori-2009Jan172004.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9fc6bd1d7362e5eb10c997d31f3ba8c0d37936b8')

  def test_13(self):
    f = open('bglib/record/testdata/agelina-nori-2009Jan180250.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '88bcd858a0eb113fc6a176a39a12cedc5847a46d')

  def test_14(self):
    f = open('bglib/record/testdata/akaBOB-nori-2009Jan221158.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1ef753c7dadd03e098def968fd1b799e7c384939')

  def test_15(self):
    f = open('bglib/record/testdata/akaBOB-nori-2009Jan251136.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4929aa05d0e873144c696e4457fbf7f45c2a9415')

  def test_16(self):
    f = open('bglib/record/testdata/Amirrr-nori-2009Feb151603.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4b210cdd96ba62b6848dbbcc35df9c34fe0be94d')

  def test_17(self):
    f = open('bglib/record/testdata/AnaGabriela-nori-2009Mar222021.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '50958974bd266a1afa9f58bfee0f6631aa90d96c')

  def test_18(self):
    f = open('bglib/record/testdata/AnaGabriela-nori-2009Mar222033.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4558e93c1b64fdc5f9527a4af0e8bb7903447803')

  def test_19(self):
    f = open('bglib/record/testdata/AnaGabriela-nori-2009Mar222052.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fcc8f076daaa025f91680bf4116e51dcb3b7f8a4')

  def test_20(self):
    f = open('bglib/record/testdata/AnaGabriela-nori-2009Mar222057.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c8acbcfa775e7820d71a82c1ed92986fbf80b614')

  def test_21(self):
    f = open('bglib/record/testdata/Antoinette-nori-2009Feb141132.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '51577287096479e06a7413488c20717c30eaa6bb')

  def test_22(self):
    f = open('bglib/record/testdata/Antoinette-nori-2009Jan261745.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '31536d3251d4154b2514f1b7c7509e3431e3f960')

  def test_23(self):
    f = open('bglib/record/testdata/asasan-nori-2009Jan172209.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f4dbe8d37c4ca29148a12967ac24f74e8af57fe1')

  def test_24(self):
    f = open('bglib/record/testdata/asasan-nori-2009Jan212154.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ef8eb4731f7263dde55eafb62c4c94bf6a90edac')

  def test_25(self):
    f = open('bglib/record/testdata/Beja-nori-2009Feb041917.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '19b6d6b1d83325efcffffd49c87bc3082c829c80')

  def test_26(self):
    f = open('bglib/record/testdata/besiktas-nori-2009Jan222026.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'b1b0582da8f976acf3ed7585172a5f6b915f9671')

  def test_27(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Apr071735.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0472ca10faa4eb0098a7a63d2c4ba4023d4042b0')

  def test_28(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Apr152320.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f61ff7675ced978e170c1946d8763b82698caabb')

  def test_29(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Feb141208.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1e52c6b17f631651bcd3d1ec45a676cb5eb81945')

  def test_30(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Feb221822.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2d69573626fefb11c65f3a958b6c3fd0ddf9ebfc')

  def test_31(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Feb261959.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '36157a6ab37157f51c1ef00a86734731091addd3')

  def test_32(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Jan172304.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1a1935354a0c1cdaf17aae183e97dd8739a5edaa')

  def test_33(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Jan181115.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '861989169a877a23200c1614602bfa04f059091e')

  def test_34(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Jan292154.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8dc9064df80ca9ede1b0f3aee5a1ea111946382b')

  def test_35(self):
    f = open('bglib/record/testdata/BlueNote-nori-2009Mar292035.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0f1ca85c4f105c50e7f3da14c71bb5b8888e1509')

  def test_36(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Apr182228.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7dc0974015516a35b85d54bd30b8a1416e5e13c5')

  def test_37(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Feb221756.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '62bad14a410673b65bd768462f97de38534951fa')

  def test_38(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Jan251017.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '384b89f9dcb373d9fceb910664e97a87917195b1')

  def test_39(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Jan252116.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '57966329df631cc07e43f3d7b221dd261b7bb9ee')

  def test_40(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Jan252132.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a7ebf7a52a7e56eae8223a950f7a8be4fbc896c5')

  def test_41(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Jan282107.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0b831e0cb551e7db79d133a29ee03d1877fa9ad3')

  def test_42(self):
    f = open('bglib/record/testdata/BoardLord-nori-2009Jan282121.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e4f7bc06d2d93155925b0dc9bb9ace507e669d32')

  def test_43(self):
    f = open('bglib/record/testdata/Bobkatt-nori-2009Apr112214.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8acfb1e28a1b52b9482d8db6d826bd86268eae40')

  def test_44(self):
    f = open('bglib/record/testdata/Bobkatt-nori-2009Apr162200.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd7ee1b6570c1dac3cad46d928d4d02cd89d9d52e')

  def test_45(self):
    f = open('bglib/record/testdata/Bobkatt-nori-2009Mar082204.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e04f789f1cd03eb56ca0f18c7106a5cc658fc179')

  def test_46(self):
    f = open('bglib/record/testdata/budtheguy-nori-2009Jan161232.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'cf247021a42829e2137f6bda987f42dd2fa742a0')

  def test_47(self):
    f = open('bglib/record/testdata/budtheguy-nori-2009Jan161244.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a6b0833f206a83881d25666a4c2f866f3efe5d8c')

  def test_48(self):
    f = open('bglib/record/testdata/budtheguy-nori-2009Jan241725.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8776464a3d759c48e16ad8665a7cd45684500d9a')

  def test_49(self):
    f = open('bglib/record/testdata/budtheguy-nori-2009Jan241747.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '38b6778abbd199e8a64178af56b6086fb8a0a45f')

  def test_50(self):
    f = open('bglib/record/testdata/cameron-nori-2009Jan302246.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c3ea1ea929041eb9d3a978f8d539917257350d66')

  def test_51(self):
    f = open('bglib/record/testdata/cameron-nori-2009Mar082233.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'edcfaceb225ec2f2f6dae71a41a4ffa3f0e4a4ca')

  def test_52(self):
    f = open('bglib/record/testdata/Carlosmx-nori-2009Jan191118.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fac7082f0528be9e9e548a084d053244a80579e5')

  def test_53(self):
    f = open('bglib/record/testdata/catman-nori-2009Mar092338.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3cc1e6049431ee5fd9f02f33a4dde699a1aa15a9')

  def test_54(self):
    f = open('bglib/record/testdata/charlie11-nori-2009Feb141749.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3cc75df41c6f03d4008a3ab50b8c97df0cdec57c')

  def test_55(self):
    f = open('bglib/record/testdata/CharlieBrown-nori-2009Jan171135.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a011d5d566c6f6d0cffe6cdf8884ba70f21a9192')

  def test_56(self):
    f = open('bglib/record/testdata/chezyh-nori-2009Mar132207.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2e049b306636bf1e864aee47b2bf4fc670404f53')

  def test_57(self):
    f = open('bglib/record/testdata/ChiefEM422-nori-2009Jan301101.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4d4b3748a91caa1f77f197639e123f0234d4fe06')

  def test_58(self):
    f = open('bglib/record/testdata/ChiefEM422-nori-2009Mar222126.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7ba0b0193ebf47f46f327153d8677b9ac8d42631')

  def test_59(self):
    f = open('bglib/record/testdata/chilidoog-nori-2009Jan151928.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6b87937ce755e3017537e1dc59a660cb2c8e1dda')

  def test_60(self):
    f = open('bglib/record/testdata/chilidoog-nori-2009Jan301125.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f28ad576a807dbb3c8e391a71c3ad19183190ff1')

  def test_61(self):
    f = open('bglib/record/testdata/civilman-nori-2009Feb261556.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c0806e97c37c8ad4c01c5fb1ccce519a1dffcb18')

  def test_62(self):
    f = open('bglib/record/testdata/conium-nori-2009Jan172125.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '474c17f6b3ddaf852115886bf3c3b2ef41db6727')

  def test_63(self):
    f = open('bglib/record/testdata/conium-nori-2009Mar012105.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '090e39ffcefd2b4428eed10874d0de8febe3f805')

  def test_64(self):
    f = open('bglib/record/testdata/Coolrey-nori-2009Jan292221.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8f64d5ba80437515682367e09c304505e640c8f4')

  def test_65(self):
    f = open('bglib/record/testdata/cyep-nori-2009Feb141109.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '390e9e135e92cf2b9690716dda3a24e477df03ad')

  def test_66(self):
    f = open('bglib/record/testdata/cyep-nori-2009Jan171535.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '123361ed09e79656d2d186b42bc14599a5c907f1')

  def test_67(self):
    f = open('bglib/record/testdata/cyep-nori-2009Jan251213.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd33d98074b470c47e3b4a15fa8824ffe1ed189d5')

  def test_68(self):
    f = open('bglib/record/testdata/d7-nori-2009Mar122046.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'dabf89fb71c70e28cb7d4b8f9168ac82fb71875c')

  def test_69(self):
    f = open('bglib/record/testdata/d7-nori-2009Mar122052.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5c4ad729c66c59c0d10fb7b300a54866b7f405d7')

  def test_70(self):
    f = open('bglib/record/testdata/DA-nori-2009Apr082037.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5658d2633d04259e1f6515cf29ba9d034d799b00')

  def test_71(self):
    f = open('bglib/record/testdata/DA-nori-2009Apr082321.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '938c1e3c80611d5c0cf8319b58ca0dd198ac2bcc')

  def test_72(self):
    f = open('bglib/record/testdata/DA-nori-2009Apr152248.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1b15de2683fb03e577552fc7c6e2964fb7669cdd')

  def test_73(self):
    f = open('bglib/record/testdata/Delphin-nori-2009Feb182159.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'b3b28095f45e12f8b61dbcda05133c0208236e89')

  def test_74(self):
    f = open('bglib/record/testdata/Delphin-nori-2009Feb182216.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '34cc33d804370a30a851bc3c594c2a7723428a34')

  def test_75(self):
    f = open('bglib/record/testdata/Delphin-nori-2009Feb182239.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e465115dc8b8a528bdd5cb21f20a7d98fb888659')

  def test_76(self):
    f = open('bglib/record/testdata/Delphin-nori-2009Jan212021.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e998bd9d10b53dca000667d4efbc0fe13f713177')

  def test_77(self):
    f = open('bglib/record/testdata/dinaraz-nori-2009Apr082007.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e5fa9a8666d89cd9a328e9e4ca80858e628b2b17')

  def test_78(self):
    f = open('bglib/record/testdata/dinaraz-nori-2009Mar050907.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c13cbf8f0681e4a34b78c7717beb25c934bb1171')

  def test_79(self):
    f = open('bglib/record/testdata/ebiten-nori-2009Feb141820.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6b5b48d663b09e10c8ab526c117bbfd719e952e1')

  def test_80(self):
    f = open('bglib/record/testdata/evi2000hu-nori-2009Jan211936.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9f441e952dd1baf5a6c7b34816827f535df29682')

  def test_81(self):
    f = open('bglib/record/testdata/FractalMan-nori-2009Apr142355.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '151743079a8ed206709ed007871fcb60a4ddcad4')

  def test_82(self):
    f = open('bglib/record/testdata/GrafDracula-nori-2009Feb041957.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4240476c2605b9adef78fe2d90ed9c9961d57f78')

  def test_83(self):
    f = open('bglib/record/testdata/GrafDracula-nori-2009Jan151918.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd0ccbf31349920126e4d1abadee6f0d3735d8f65')

  def test_84(self):
    f = open('bglib/record/testdata/GrafDracula-nori-2009Jan172203.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '50e76e4d325cf4a021916c81a76d1771c1317802')

  def test_85(self):
    f = open('bglib/record/testdata/hanimeli60-nori-2009Jan202012.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '46152af20e4e1a3b88988237d1c23a186bec205e')

  def test_86(self):
    f = open('bglib/record/testdata/HansK-nori-2009Feb030121.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7009813ed384414c3235e326dc47a51cf9a58997')

  def test_87(self):
    f = open('bglib/record/testdata/HansK-nori-2009Jan171952.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8d1152152287c33924e4c993549a529f85af7695')

  def test_88(self):
    f = open('bglib/record/testdata/HansK-nori-2009Jan240140.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ff8249f6ba26d0f4cc2f509580a5ab66c7afc896')

  def test_89(self):
    f = open('bglib/record/testdata/HansK-nori-2009Jan251035.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '505726e28d6f1ccebdad9af2c7d826c4a4504f7b')

  def test_90(self):
    f = open('bglib/record/testdata/HansK-nori-2009Jan270318.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '39a3049b047c027493e4951e825a43152f829302')

  def test_91(self):
    f = open('bglib/record/testdata/HarryDiculus-nori-2009Jan192013.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0019a81417ae4a6dbb7bca94c485c9a0364e0377')

  def test_92(self):
    f = open('bglib/record/testdata/HarryDiculus-nori-2009Jan192034.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '26e2acbc6f3836ddaf11060d6596c6afd1eda008')

  def test_93(self):
    f = open('bglib/record/testdata/HarryDiculus-nori-2009Jan282044.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '70496fb6fc4a13748b7fca8854adfd2f003c1a1d')

  def test_94(self):
    f = open('bglib/record/testdata/hockeyfan-nori-2009Apr151207.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a884d2b7668cfe0c7aab23bcf962b4459d83429d')

  def test_95(self):
    f = open('bglib/record/testdata/hockeyfan-nori-2009Apr152338.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '24f5f2ae7340769accaf37219f89a8ce46363d9c')

  def test_96(self):
    f = open('bglib/record/testdata/hockeyfan-nori-2009Jan171243.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2cb4992a096f92ebed59819e3668e2c56f640fc5')

  def test_97(self):
    f = open('bglib/record/testdata/hockeyfan-nori-2009Jan180138.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '64b11272400e76d69059c847252c717a962c90dd')

  def test_98(self):
    f = open('bglib/record/testdata/HooShanG-nori-2009Jan291822.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '148052fd9eebdc3cbd2112ea00b601b4a306b8c3')

  def test_99(self):
    f = open('bglib/record/testdata/HooShanG-nori-2009Jan291842.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '18508b1e12f4a1507b4fcfb78dfab932139698bc')

  def test_100(self):
    f = open('bglib/record/testdata/HooShanG-nori-2009Jan291902.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2fae74517e8323c080e2af21f7cdce01d87c451a')

  def test_101(self):
    f = open('bglib/record/testdata/hugow-nori-2009Feb220456.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd3bf08c9498763e034cb5d9b4cc623656f2aaa88')

  def test_102(self):
    f = open('bglib/record/testdata/iceman5691-nori-2009Feb011820.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'de52019092d7b0448ccd720b0a6aab634dbbd2b4')

  def test_103(self):
    f = open('bglib/record/testdata/iceman5691-nori-2009Feb021234.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ce2122a11e01b5ec72238b392739e78d4dab2cc3')

  def test_104(self):
    f = open('bglib/record/testdata/iceman5691-nori-2009Jan252221.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '41a9ef6418218481a7e0b126e737e46047c67f67')

  def test_105(self):
    f = open('bglib/record/testdata/IHaveTwo-nori-2009Feb011211.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd750f639906b2f2ead4389664d2bb8192b7f53d1')

  def test_106(self):
    f = open('bglib/record/testdata/IHaveTwo-nori-2009Mar280144.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '814c549a83ff9043ab516c14be2de772f0cd5ceb')

  def test_107(self):
    f = open('bglib/record/testdata/imagex5-nori-2009Apr172308.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8b96d63da66e8aa5101879942383184aa014ade2')

  def test_108(self):
    f = open('bglib/record/testdata/imagex5-nori-2009Mar122111.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9eabea5988ffc6bc946b12ea339a89e16174fc1d')

  def test_109(self):
    f = open('bglib/record/testdata/ITAKA-nori-2009Feb142011.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '87afca95bac3de2f3eb833fc15dd04f093e94746')

  def test_110(self):
    f = open('bglib/record/testdata/ITAKA-nori-2009Jan141753.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7eb3b21360371a1a3845465d9d223daea2bd317e')

  def test_111(self):
    f = open('bglib/record/testdata/jack6-nori-2009Jan242200.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '01dd5c7553b039c05f0d29000e0be9c42c991fe9')

  def test_112(self):
    f = open('bglib/record/testdata/Jangler-nori-2009Jan261822.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '05f4600b508e7a054c8a4b9b6b5f828409430c65')

  def test_113(self):
    f = open('bglib/record/testdata/jara-nori-2009Jan311231.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3d76823f5231476ca7abc98076ceb282ebd3f7e9')

  def test_114(self):
    f = open('bglib/record/testdata/Jerzeegirlx-nori-2009Apr151154.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '99785b0fd4e93be185c7f067b9cedc23114620bb')

  def test_115(self):
    f = open('bglib/record/testdata/Jerzeegirlx-nori-2009Feb020915.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'eb26131a66cf679f453dbe7e1c343ee694ec7384')

  def test_116(self):
    f = open('bglib/record/testdata/Jerzeegirlx-nori-2009Jan181035.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '53c54847a2ce9bebd8c585266441f55909604ff2')

  def test_117(self):
    f = open('bglib/record/testdata/Jerzeegirlx-nori-2009Jan211113.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd9519f648bde70680ff9707cc2557dabf7db47ec')

  def test_118(self):
    f = open('bglib/record/testdata/Jerzeegirlx-nori-2009Jan272128.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'af3bd8d2da72463f3993d0138bf6f530188af16e')

  def test_119(self):
    f = open('bglib/record/testdata/Juego-nori-2009Feb020859.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd3256fea0adaec57f2a14e3208838b7ec8102aa7')

  def test_120(self):
    f = open('bglib/record/testdata/Juego-nori-2009Jan161149.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd834c9162e33090f78ab92cb73be8416d25762ec')

  def test_121(self):
    f = open('bglib/record/testdata/Juego-nori-2009Jan180948.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd41abc081cd60448423a485645ab5275a46734b7')

  def test_122(self):
    f = open('bglib/record/testdata/junejuly-nori-2009Jan270259.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '49e040825b8a4147cc3e73f81703999c4974d1da')

  def test_123(self):
    f = open('bglib/record/testdata/junejuly-nori-2009Mar052212.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'dc5a4b709b79060cf95483c414f03dd98cc2754c')

  def test_124(self):
    f = open('bglib/record/testdata/JURY-nori-2009Mar012229.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1f93b6e6921ffe681c8f206f0c40c7d1f7fbb4e2')

  def test_125(self):
    f = open('bglib/record/testdata/kahveci-nori-2009Mar100000.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5538731f97ccdc6aab49442a5cbe05b517d340ee')

  def test_126(self):
    f = open('bglib/record/testdata/Kalagh-nori-2009Jan231111.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '56dec82f60b7f0eb4a3733e68918b346f51b96f4')

  def test_127(self):
    f = open('bglib/record/testdata/Kaneko-nori-2009Apr102316.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'eecd5c08f8293f56736d5f304e130ee5e173c894')

  def test_128(self):
    f = open('bglib/record/testdata/Kaneko-nori-2009Jan142040.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4ebe1628ee3a2caca89670d09dbef4d7297473ee')

  def test_129(self):
    f = open('bglib/record/testdata/KAROLINA-nori-2009Mar021928.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f04689dadf851274dd4d6a26c0b1f09e4c226b31')

  def test_130(self):
    f = open('bglib/record/testdata/kikelas-nori-2009Mar220120.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fa609993eaecf46efb4c193a30d4ae5c2b89c977')

  def test_131(self):
    f = open('bglib/record/testdata/kitacyan224-nori-2009Jan202139.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0fe239a685b3ed7a225afad93f5879f295a9e306')

  def test_132(self):
    f = open('bglib/record/testdata/Kool47-nori-2009Feb280946.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '253bc0a30a9823fb85f7e466492cd87e457cb43c')

  def test_133(self):
    f = open('bglib/record/testdata/Kopanze-nori-2009Mar012200.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '38f7ddf4d1711b04f32043587b9ee2a48e81c633')

  def test_134(self):
    f = open('bglib/record/testdata/Kopanze-nori-2009Mar012212.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '867a747a110a2cccf8cf621cab4246093011779e')

  def test_135(self):
    f = open('bglib/record/testdata/Kopanze-nori-2009Mar220108.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '13cead59e353e0f291dc7e5bf227d0960ddab918')

  def test_136(self):
    f = open('bglib/record/testdata/kopidon-nori-2009Jan221617.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7d754b82166fbc3e31c95c3cba95d45ad1cccce8')

  def test_137(self):
    f = open('bglib/record/testdata/kumari-nori-2009Mar031347.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8f1e1e0c37e341822cc4d87a20c91cfbfedc9989')

  def test_138(self):
    f = open('bglib/record/testdata/lavraki-nori-2009Jan192208.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0cf2adc7e76abc02beedf74c0d1acd76bf62b5fa')

  def test_139(self):
    f = open('bglib/record/testdata/lavraki-nori-2009Jan270243.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c755f88f452e72b8ee833af577410c7fc0701761')

  def test_140(self):
    f = open('bglib/record/testdata/lavraki-nori-2009Jan270248.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3a7aaedb96465daca3976b19997c098cc92b1f47')

  def test_141(self):
    f = open('bglib/record/testdata/london-nori-2009Feb212241.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2dc2f4dc96520d355bf717506bee2743ba3c0fb9')

  def test_142(self):
    f = open('bglib/record/testdata/lordrichard-nori-2009Jan231049.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5405128f63ee4fc431e6df8adb3b4c39e6533757')

  def test_143(self):
    f = open('bglib/record/testdata/lordrichard-nori-2009Jan251046.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e4b7212586227ca71fda702d2bf9070e9880a923')

  def test_144(self):
    f = open('bglib/record/testdata/LuckyLee-nori-2009Mar151037.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3a10263fd8883480c310ab7a7efd06d9190fc6e4')

  def test_145(self):
    f = open('bglib/record/testdata/Masa23-nori-2009Feb042052.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '34f2e63bc8b7d407d2f7335150bcfd94cf6696b8')

  def test_146(self):
    f = open('bglib/record/testdata/MASODA-nori-2009Mar181925.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fcf0e10120a17036a208f9f836d0b03ddba4ab81')

  def test_147(self):
    f = open('bglib/record/testdata/massie-nori-2009Feb072347.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3cd965eca0de23e9300b5e262392a52ad03b762c')

  def test_148(self):
    f = open('bglib/record/testdata/massie-nori-2009Feb122154.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f405011d7948c487f46e33925bc0f71aa57dc69c')

  def test_149(self):
    f = open('bglib/record/testdata/massie-nori-2009Feb132303.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'b15d2e0ce43f8a45fe2df7478a5ad7f12309732e')

  def test_150(self):
    f = open('bglib/record/testdata/massie-nori-2009Feb152158.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '33b55cdd6cc09dd3f28974acfff8571168ea0900')

  def test_151(self):
    f = open('bglib/record/testdata/massie-nori-2009Feb260143.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'acfb69b7bb1e30b1c8228987729ce507d854ba83')

  def test_152(self):
    f = open('bglib/record/testdata/massie-nori-2009Jan152030.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '10922d5a2accaf90d606d4f2b88735e1e045e02a')

  def test_153(self):
    f = open('bglib/record/testdata/massie-nori-2009Mar222043.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '1b4f1ee06d4c09780455f6864259ba68fe0456f0')

  def test_154(self):
    f = open('bglib/record/testdata/MERDOGLU-nori-2009Mar151024.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'aeced9eda8947e186e4d1ec7b4bab49893cfac1b')

  def test_155(self):
    f = open('bglib/record/testdata/MishMish-nori-2009Jan270139.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '45b4b9d8f2ebe5c3f96d41bc70b9fdd18c82ca97')

  def test_156(self):
    f = open('bglib/record/testdata/MishMish-nori-2009Jan270151.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '293162497ac63a2ad312ee4c77428b93ff4d3d44')

  def test_157(self):
    f = open('bglib/record/testdata/MishMish-nori-2009Jan270206.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8cfa4cc51a929008c3c4881eb9dd5c89df69f390')

  def test_158(self):
    f = open('bglib/record/testdata/MishMish-nori-2009Jan291255.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ccf049ba2bc0bbd1a3a10b62609ad2e331a89372')

  def test_159(self):
    f = open('bglib/record/testdata/MisterPostman-nori-2009Apr112137.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '241dbd6d7d61f79a77e8cd9383ac0749c7d6f7c6')

  def test_160(self):
    f = open('bglib/record/testdata/MLB-nori-2009Apr101951.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e09bb8b94b44926abbf9998d751ecbe0c4ddc70a')

  def test_161(self):
    f = open('bglib/record/testdata/MLB-nori-2009Mar012236.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a7496c995293621aed4d5e7f5b946bf4cf913b0c')

  def test_162(self):
    f = open('bglib/record/testdata/MochizukiMasayuki_TabataMakoto_11p_Final_090222.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '504194b490136152960597bc1c63bd4008c35b5a')

  def test_163(self):
    f = open('bglib/record/testdata/mochy-nori-2009Apr031925.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '449e7aff1b2074a7c81bfa01046c3663d064a7b9')

  def test_164(self):
    f = open('bglib/record/testdata/mogulero-nori-2009Jan302146.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '769b7883a519f0bf105352bc7a72a5741634cce7')

  def test_165(self):
    f = open('bglib/record/testdata/MONSTER-nori-2009Apr112157.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e8b3c8bbdc92540b68422971c9a48525270c4207')

  def test_166(self):
    f = open('bglib/record/testdata/MONSTER-nori-2009Jan302109.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2336bac5e79268e3678374521dc2fcc0f0d89de2')

  def test_167(self):
    f = open('bglib/record/testdata/MONSTER-nori-2009Jan302119.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'dca925f59b5dde777e113bc3eddf9b2acfc708c3')

  def test_168(self):
    f = open('bglib/record/testdata/moonlightkiss-nori-2009Jan151545.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8d81e5b1982a6eb3854ee8e9ff00a229fe5580aa')

  def test_169(self):
    f = open('bglib/record/testdata/nader-nori-2009Jan212039.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '22efe03a04b79c08ca4896d2b4b8e1bf988da5a0')

  def test_170(self):
    f = open('bglib/record/testdata/NAMKHA-nori-2009Jan252204.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2ed9772fde31b26717ad4e4a343d25f344aa445f')

  def test_171(self):
    f = open('bglib/record/testdata/NashHomeplace2-nori-2009Apr182209.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '32c9ad337e506470945375454b7915f6be6159df')

  def test_172(self):
    f = open('bglib/record/testdata/nenehatun-nori-2009Jan172014.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'edb22affe7ede6b9c624cd312c673c8deac084fa')

  def test_173(self):
    f = open('bglib/record/testdata/nicksbar-nori-2009Jan302316.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f2ad0374b6b450c84dc48574ccaca93098848f66')

  def test_174(self):
    f = open('bglib/record/testdata/NIUSHA-nori-2009Jan252141.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'dfee285e9fa184c95c1ba21873ec406a15866efb')

  def test_175(self):
    f = open('bglib/record/testdata/NIUSHA-nori-2009Mar220029.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6cefcf7b1380a8305f3c8cf862b33ea231ee7ce8')

  def test_176(self):
    f = open('bglib/record/testdata/Noctogammon-nori-2009Feb012057.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8009b1e7a26443e5954450b298d6e7a2eb939fec')

  def test_177(self):
    f = open('bglib/record/testdata/Noctogammon-nori-2009Feb012114.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd730d2be411266ef4aee0b909ac9d8734f4111f3')

  def test_178(self):
    f = open('bglib/record/testdata/Noctogammon-nori-2009Jan242219.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0a982d6557091e78febb620c977d9406f73f4393')

  def test_179(self):
    f = open('bglib/record/testdata/Noctogammon-nori-2009Jan302056.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7c707a00ae5fa288cb521f71be4d025af43cbaa0')

  def test_180(self):
    f = open('bglib/record/testdata/OKPHTHKOS-nori-2009Mar151009.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'bcba4a3c76e5363fc335aa388af7a1cff8163ded')

  def test_181(self):
    f = open('bglib/record/testdata/othello-nori-2009Apr162224.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3c0dfb06d37f9bf3c306e666d0ac41e7fb7d7654')

  def test_182(self):
    f = open('bglib/record/testdata/othello-nori-2009Apr172336.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e6f1f607ad0c8bae2d1d1938e594b8d43ccdc2f2')

  def test_183(self):
    f = open('bglib/record/testdata/othello-nori-2009Jan282152.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '054a176df51a593a46bf096d5a763e8a197e2aea')

  def test_184(self):
    f = open('bglib/record/testdata/othello-nori-2009Mar281007.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e511e3b18b77f03a9018fe459d89ae8b44d3b683')

  def test_185(self):
    f = open('bglib/record/testdata/parvizrokh-nori-2009Feb192251.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '57da99fc40c1fe2b7b308570d2648d4830fd6641')

  def test_186(self):
    f = open('bglib/record/testdata/Petrovich-nori-2009Apr191048.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6b89a0f8aa25f9759d43f275e3e7b2cbaf61c3e3')

  def test_187(self):
    f = open('bglib/record/testdata/peyman76-nori-2009Jan172103.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ad0cb857686de4258d9481196d9bdc1e4c99bf14')

  def test_188(self):
    f = open('bglib/record/testdata/PghPete-nori-2009Jan242317.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'eabd3d2f7fcc63ce48a15ecf144455c3e0141f62')

  def test_189(self):
    f = open('bglib/record/testdata/PghPete-nori-2009Jan242323.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ba5758402224fbd4b3d51ecb43c666e90ea2858b')

  def test_190(self):
    f = open('bglib/record/testdata/PghPete-nori-2009Jan301029.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '66f54ca2fd2805e56b42552a665260067a59d778')

  def test_191(self):
    f = open('bglib/record/testdata/Pipshark-nori-2009Feb011731.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e935caa7a09e14a0c53711a19a39891bbb1e28ef')

  def test_192(self):
    f = open('bglib/record/testdata/Pipshark-nori-2009Jan211100.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '578e8b6716abcdab558893e74a83285fd7b61fc5')

  def test_193(self):
    f = open('bglib/record/testdata/pit2-nori-2009Mar072231.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'c3858d22726ddc8b9f567a420b2db3455df62c50')

  def test_194(self):
    f = open('bglib/record/testdata/Presentable-nori-2009Feb020823.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '49713df61bf63dcff2306cd910637a4cd83f3be2')

  def test_195(self):
    f = open('bglib/record/testdata/Primer888-nori-2009Feb192235.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8c79507d11e8e5ce11aff7872ebd8da5eb07be72')

  def test_196(self):
    f = open('bglib/record/testdata/Primer888-nori-2009Jan240158.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '382006bbc6499264eae55ae8ce9b889580cc4bf7')

  def test_197(self):
    f = open('bglib/record/testdata/py199-nori-2009Jan171407.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'caf058932f53dd4cdf06553a133655a86e63a948')

  def test_198(self):
    f = open('bglib/record/testdata/py199-nori-2009Jan171414.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ba3e63ef6d71bb72eb998ea7fa0fcf2040782111')

  def test_199(self):
    f = open('bglib/record/testdata/py199-nori-2009Jan171420.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '09b20ff979590e93dabc90392fa58a4cdd340e4b')

  def test_200(self):
    f = open('bglib/record/testdata/py199-nori-2009Jan311549.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5e3cbb2af57aabffa041857700250cfcee053359')

  def test_201(self):
    f = open('bglib/record/testdata/py199-nori-2009Jan312258.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '962dc0d4e59fbd17d57d560c7c087d8c076492c8')

  def test_202(self):
    f = open('bglib/record/testdata/ramune-nori-2009Apr172255.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2ee52701649f5e9a5f02373cd2123fed31a89b16')

  def test_203(self):
    f = open('bglib/record/testdata/ramune-nori-2009Feb071252.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '042d49f907b52c2c25edc77e52123024c2a387b1')

  def test_204(self):
    f = open('bglib/record/testdata/ramune-nori-2009Jan202049.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '09d8b30b8f63a84035fe5eeea1e128705b840e5e')

  def test_205(self):
    f = open('bglib/record/testdata/ramune-nori-2009Jan202112.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '47c8f18d7a731e93b0a1351bd60ec96e303d8d09')

  def test_206(self):
    f = open('bglib/record/testdata/ramune-nori-2009Jan272203.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '3bd7006aff6539f900eee838b85b505819e2da35')

  def test_207(self):
    f = open('bglib/record/testdata/ramune-nori-2009Jan272223.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5845a911325e184393d40041253c9603b0e899be')

  def test_208(self):
    f = open('bglib/record/testdata/ramune-nori-2009Mar132217.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2a08590b6aeb7217e43146e0598a1b2487b98132')

  def test_209(self):
    f = open('bglib/record/testdata/RareDiamondGem-nori-2009Feb260212.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'f7f89539c28e9cea31109dc706fbbaba194bbf4a')

  def test_210(self):
    f = open('bglib/record/testdata/RareDiamondGem-nori-2009Jan241243.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fafaaa6caa34efa97cc717adb48351169c3ab8af')

  def test_211(self):
    f = open('bglib/record/testdata/RareDiamondGem-nori-2009Jan241327.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd92d13d2a76ad8afca7948dda92fa03c32600a39')

  def test_212(self):
    f = open('bglib/record/testdata/replicamaster-nori-2009Feb012258.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'ef70f22d758d1a1f23a3cc28b707e888e37bcf0b')

  def test_213(self):
    f = open('bglib/record/testdata/replicamaster-nori-2009Jan252101.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2fa8f2ec6854217c189f826eb4a46ccc3e1b78dd')

  def test_214(self):
    f = open('bglib/record/testdata/replicamaster-nori-2009Mar051326.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6c4521cf6b577f5347981cff0f7752291677e91b')

  def test_215(self):
    f = open('bglib/record/testdata/ROYHO-nori-2009Feb212313.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '4e3aba2184310b03d045c73df76d6e6a8f108981')

  def test_216(self):
    f = open('bglib/record/testdata/ROYHO-nori-2009Jan312325.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd74854f0cda74a86105e17d6d0d5879142ddcac9')

  def test_217(self):
    f = open('bglib/record/testdata/Rusty-nori-2009Feb141124.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9a25b9a85425cc0b99ef5cd1110bf32b29e47e89')

  def test_218(self):
    f = open('bglib/record/testdata/sam64-nori-2009Mar032235.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e8a92706016af714cff1f8b1f2f6465626b5b239')

  def test_219(self):
    f = open('bglib/record/testdata/sArAmarch-nori-2009Jan282016.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '7c9f8d6eb057e73e6e6616d2dc2234638ae3387d')

  def test_220(self):
    f = open('bglib/record/testdata/sArAmarch-nori-2009Jan282022.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '9c3a3f14ef21c05dd8ba19faa1178357cd051817')

  def test_221(self):
    f = open('bglib/record/testdata/Sarj51-nori-2009Apr112145.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5d317efec8a68222c35d443bfb571c04d30a3770')

  def test_222(self):
    f = open('bglib/record/testdata/Seatrik-nori-2009Apr082307.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a6ad728ce171755b11de953ed17c216c1471b462')

  def test_223(self):
    f = open('bglib/record/testdata/SgtPepper-nori-2009Mar082215.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a422856a0cb7ed6f8815c274043d9be58e9d1655')

  def test_224(self):
    f = open('bglib/record/testdata/shirofukurou-nori-2009Mar220018.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8dc01f046ca3fdd2a94d7179115c8ad8307303be')

  def test_225(self):
    f = open('bglib/record/testdata/SkiiBoots-nori-2009Mar280956.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '025796e1e045dd5dc9f8ef1253212e88596103a1')

  def test_226(self):
    f = open('bglib/record/testdata/SkyeBlue-nori-2009Feb280917.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e121e7e1f0376620bcdb15858bb3756d423d1a75')

  def test_227(self):
    f = open('bglib/record/testdata/snua-nori-2009Mar282031.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'a029c3367edbcb8123195c064adb280f1f072b99')

  def test_228(self):
    f = open('bglib/record/testdata/SSYEKTA-nori-2009Jan141810.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6511acb9f13944728ee20bab56e39ee278017f75')

  def test_229(self):
    f = open('bglib/record/testdata/SSYEKTA-nori-2009Jan141830.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '8833232aa2538c24c535db552b77cd047c3c7896')

  def test_230(self):
    f = open('bglib/record/testdata/SSYEKTA-nori-2009Jan141902.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '334cceceb3a68a847287579e5f11985410ff0a26')

  def test_231(self):
    f = open('bglib/record/testdata/SSYEKTA-nori-2009Jan180317.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '289350dce0afc221a9124a0d08363da2680a3812')

  def test_232(self):
    f = open('bglib/record/testdata/superlady-nori-2009Jan251005.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '58b88d9865d5f675a837268a71af368244b60dfd')

  def test_233(self):
    f = open('bglib/record/testdata/svartan-nori-2009Jan152010.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'bbc74b775a8824f2d1abf50bb4ef47975a1f816c')

  def test_234(self):
    f = open('bglib/record/testdata/sweetyM-nori-2009Feb280905.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'fb301f1f1e55c5f53cb93502bf6a7ef7cb3dfb17')

  def test_235(self):
    f = open('bglib/record/testdata/swonderful-nori-2009Mar220056.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '33f1d068f5e4f70201ed0e8a3b43ee741c4f1993')

  def test_236(self):
    f = open('bglib/record/testdata/tamtam2784-nori-2009Jan151125.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e972d1efde6b3f7736ca09b38ff70a7b75475f3c')

  def test_237(self):
    f = open('bglib/record/testdata/tamtam2784-nori-2009Jan282351.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e495521426492ed6f1c06ca941eed5c67f23c4cc')

  def test_238(self):
    f = open('bglib/record/testdata/tavison-nori-2009Mar052149.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2b6ebb456a0a5efe58f23cde694056121faa9fb5')

  def test_239(self):
    f = open('bglib/record/testdata/terrific1-nori-2009Jan212214.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '6e354637caa6e17200c6a44702152f1b7fc13d93')

  def test_240(self):
    f = open('bglib/record/testdata/texmex-nori-2009Feb011756.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'bb7ed8e9ed9908b8831f6eb9cde5c4f33be1f8bd')

  def test_241(self):
    f = open('bglib/record/testdata/texmex-nori-2009Jan251029.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '41a65cd22ebf069234cbbf0df43e3ddb6978195f')

  def test_242(self):
    f = open('bglib/record/testdata/theking-nori-2009Mar181946.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2e7d072630abb96e25790d20a2a93f0686762e1f')

  def test_243(self):
    f = open('bglib/record/testdata/theking-nori-2009Mar252357.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '282e7b81d94221fb3da56e1be25668ef6e9a95b4')

  def test_244(self):
    f = open('bglib/record/testdata/Trojan-nori-2009Feb032106.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'e02198758472ff0ccb67fb2126a3fb979101ce04')

  def test_245(self):
    f = open('bglib/record/testdata/Trojan-nori-2009Feb132215.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '440455a8dc66c626b5a3fbbe44f28a62a4ba7488')

  def test_246(self):
    f = open('bglib/record/testdata/Trojan-nori-2009Jan181948.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '31cd4cb53d82bd3ad2ece05411a6baedf3609b49')

  def test_247(self):
    f = open('bglib/record/testdata/VaGrant1-nori-2009Mar050924.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '31e5504c29b37d8d66e3a2410bf2633acd5d42a0')

  def test_248(self):
    f = open('bglib/record/testdata/vegasman-nori-2009Jan270311.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'b43089615336249b0537a76d1143dc4856adf629')

  def test_249(self):
    f = open('bglib/record/testdata/vegasman-nori-2009Jan311203.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '234a052e0f2424c43afb0e7333c8f9c69b0fc625')

  def test_250(self):
    f = open('bglib/record/testdata/Wakagashira-nori-2009Feb092110.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '76f9025eb140ed88e2d45ee3e50b4a6c9c1b669b')

  def test_251(self):
    f = open('bglib/record/testdata/Wakagashira-nori-2009Feb092123.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'bf5dd136e65e59a204dfd8ccc8be3263a6ece28e')

  def test_252(self):
    f = open('bglib/record/testdata/willvlc-nori-2009Mar021903.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '5681f68e020b739834eb12ece0d69c2811c7a81a')

  def test_253(self):
    f = open('bglib/record/testdata/zaman65-nori-2009Jan291927.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'd798155b2da2dcf8ca9bbeedf9902fac8b88cafc')

  def test_254(self):
    f = open('bglib/record/testdata/Zendik-nori-2009Jan231708.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '0e99905dd8607cbde709c6b075ecd5ff6c40f5d3')

  def test_255(self):
    f = open('bglib/record/testdata/zooecium-nori-2009Feb011238.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     'df24ad323c036c9a3641265f4a0f6211206d9bb3')

  def test_256(self):
    f = open('bglib/record/testdata/zoonk-nori-2009Jan151857.txt')
    v = Validator(f)
    h = v.validate()
    self.assertEqual(h.hexdigest(),
                     '2b54d9c741434b721d358caaa0143d736adacf8f')

